version: "3"
services:
  #device registry system
  cdrsi:
    image: drsi
    ports:
      - 8080:8080
    expose:
      - 8080
    container_name: cdrsi

  #Telegram
  ct:
    image: ti
    links:
      - cdrsi
    depends_on:
      - cdrsi

  #Patient monitor
  cpm:
    image: pmi
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #Patient device analyzer
  cpai:
    image: pdai
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #temperature patient room
  ctpri:
    image: tpri
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #light patient room monitor
  clprmi:
    image: lprmi
    stdin_open: true
    tty: true
    links:
      - cdrsi
    depends_on:
      - cdrsi

  #temperature common room
  ctcri:
    image: tcri
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #fibbrilation
  cf:
    image: fi
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true
  
  #data analysis
  cda:
    image: dai
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #thinkspeek adaptor
  ctsai:
    image: tsai
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #system terminal
  csti:
    image: sti
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    restart: always
    #tty: true

# raspberry emulator
#  crei : 
#    image : rei
#    links : 
#      - cdrsi
#    depends_on :
#      - cdrsi
#    stdin_open : true
#    tty : true
