#version: 3
#name: smartnursing
volumes:
  drs:

services:
  #device registry system
  cdrsi:

    image: smartnursing-drsi
    build: ./device-registry-system
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - drs:/usr/app/

    #container_name: cdrsi

  #Telegram
  ct:
    
    image: smartnursing-ti
    build: ./telegram-bot
    links:
      - cdrsi
    depends_on:
      - cdrsi

  #Patient monitor
  cpm:
    build: ./patient-monitor
    image: smartnursing-pmi
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #Patient device analyzer
  cpai:
    image: smartnursing-pdai
    build: ./patient-device-analyzer
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #temperature patient room
  ctpri:
    image: smartnursing-tpri
    build: ./temperature-patient-room
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #light patient room monitor
  clprmi:
    image: smartnursing-lprmi
    build: ./light-patient-room-monitor
    stdin_open: true
    tty: true
    links:
      - cdrsi
    depends_on:
      - cdrsi

  #temperature common room
  ctcri:
    image: smartnursing-tcri
    build: ./temperature-common-room
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #fibrillation
  cf:
    image: smartnursing-fi
    build: ./fibrillation
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true
  
  #data analysis
  cda:
    build: ./data-analysis
    image: smartnursing-dai
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #thingspeak adaptor
  ctsai:
    image: smartnursing-tsai
    build: ./thing-speak-adaptor
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #system terminal
  csti:
    build: ./terminal
    image: smartnursing-sti
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    #restart: always

  #raspberry emulator
  crei : 
    image : smartnursing-rei
    build: ./raspberry-emulator
    links : 
      - cdrsi
    depends_on :
      - cdrsi
    stdin_open : true
    tty : true
