version: "3"
name: "smartclinic"
services:
  #device registry system
  cdrsi:
    image: smartclinic-drsi
    build: ./device-registry-system
    ports:
      - 8080:8080
    expose:
      - 8080
    #container_name: cdrsi

  #Telegram
  ct:
    image: smartclinic-ti
    build: ./TelegramBot
    links:
      - cdrsi
    depends_on:
      - cdrsi

  #Patient monitor
  cpm:
    build: ./PatientMonitor
    image: smartclinic-pmi
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #Patient device analyzer
  cpai:
    image: smartclinic-pdai
    build: ./PatientDeviceAnalyzer
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #temperature patient room
  ctpri:
    image: smartclinic-tpri
    build: ./temperature-patient-room
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #light patient room monitor
  clprmi:
    image: smartclinic-lprmi
    build: ./light-patient-room-monitor
    #stdin_open: true
    #tty: true
    links:
      - cdrsi
    depends_on:
      - cdrsi

  #temperature common room
  ctcri:
    image: smartclinic-tcri
    build: ./temperature-common-room
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #fibrillation
  cf:
    image: smartclinic-fi
    build: ./Fibrillation
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true
  
  #data analysis
  cda:
    build: ./DataAnalysis
    image: smartclinic-dai
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #thingspeak adaptor
  ctsai:
    image: smartclinic-tsai
    build: ./thingSpeakAdaptor
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    tty: true

  #system terminal
  csti:
    build: ./Terminal
    image: smartclinic-sti
    links:
      - cdrsi
    depends_on:
      - cdrsi
    stdin_open: true
    #restart: always

  #raspberry emulator
  crei : 
    image : smartclinic-rei
    build: ./raspberry-emulator
    links : 
      - cdrsi
    depends_on :
      - cdrsi
    stdin_open : true
    tty : true
